--- 
auth_file: murlsh_users
cache_entitystore: file:tmp/cache/rack/body
cache_metastore: file:tmp/cache/rack/meta
css_files: 
- css/jquery.jgrowl.css
- css/screen.css
db: 
  adapter: sqlite3
  database: murlsh.db
feed_file: atom.atom
gravatar_size: 32
js_files: 
- js/jquery-1.5.1.min.js
- js/jquery.jgrowl_compressed.js
- js/twitter-text-1.3.1.js
- js/js.js
meta_tag_description: 
meta_tag_verify-v1: 
meta_tag_viewport: width=device-width,minimum-scale=1.0,maximum-scale=1.0
num_posts_feed: 25
num_posts_page: 25
page_title: murlsh
pubsubhubbub_hubs: []

quick_search: 
  audio: .mp3 .ogg
  code: code.google.com github.com
  images: .png .gif .jpeg .jpg
  tweets: twitter.com
  video: hulu.com vimeo.com www.ted.com youtube.com
  wikipedia: wikipedia.org
root_url: http://urls.matthewm.boedicker.org/
s3_bucket: 
s3_id: 
s3_secret: 
show_names: true
thumbnail_max_side: 90
user_agent: murlsh (https://github.com/mmb/murlsh)
