--- 
auth_file: murlsh_users
description: URLs found interesting by Matthew M. Boedicker
db_file: murlsh.db
feed_file: atom.xml
google_verify: 
gravatar_size: 32
num_posts_feed: 25
num_posts_page: 100
page_title: mmb url share
root_url: http://urls.matthewm.boedicker.org/
img_prefix: img/
js_prefix: js/
swf_prefix: swf/
css_files:
- jquery.jgrowl.css
- screen.css
