--- 
auth_file: murlsh_users
css_files: 
- css/jquery.jgrowl.css
- css/screen.css
db_file: murlsh.db
description: URLs found interesting by Matthew M. Boedicker
feed_file: atom.xml
google_verify: 
gravatar_size: 32
js_files: 
- js/jquery-1.4.2.min.js
- js/jquery.cookie.js
- js/jquery.jgrowl_compressed.js
- js/js.js
num_posts_feed: 25
num_posts_page: 100
page_title: mmb url share
pubsubhubbub_hubs: []

root_url: http://urls.matthewm.boedicker.org/
show_names: true
