--- 
auth_file: murlsh_users
description: URLs found interesting by Matthew M. Boedicker
db_file: murlsh.db
feed_file: atom.xml
google_verify: 
gravatar_size: 32
num_posts_feed: 25
num_posts_page: 100
page_title: mmb url share
root_url: http://urls.matthewm.boedicker.org/
css_files:
- css/jquery.jgrowl.css
- css/screen.css
js_files:
- js/jquery-1.4.1.min.js
- js/jquery.cookie.js
- js/jquery.jgrowl_compressed.js
- js/js.js
