--- 
auth_file: murlsh_users
cache_entitystore: file:tmp/cache/rack/body
cache_metastore: file:tmp/cache/rack/meta
config_js: 
- thumb_locators
css_files: 
- css/jquery.jgrowl.css
- css/screen.css
db_file: murlsh.db
feed_file: atom.xml
flickr_api_key: 
gravatar_size: 32
js_files: 
- js/jquery-1.4.2.min.js
- js/jquery.jgrowl_compressed.js
- js/js.js
meta_tag_description: URLs found interesting by Matthew M. Boedicker
meta_tag_verify-v1: 
meta_tag_viewport: width=device-width,minimum-scale=1.0,maximum-scale=1.0
num_posts_feed: 25
num_posts_page: 100
page_title: mmb url share
pubsubhubbub_hubs: []

root_url: http://urls.matthewm.boedicker.org/
show_names: true
thumb_locators:
  (http:\/\/(cgi\.)?ebay\.(com|co\.uk)\/).*: $1apple-touch-icon.png
  (http:\/\/blog\.makezine\.com\/).*: $1apple-touch-icon.png
  (http:\/\/en\.wikipedia\.org\/).*: $1apple-touch-icon.png
  (http:\/\/github\.com\/).*: $1apple-touch-icon.png
  (http:\/\/stackoverflow\.com\/).*: $1apple-touch-icon.png
  (http:\/\/www\.nytimes\.com\/).*: $1apple-touch-icon.png
  (http:\/\/www\.wired\.com\/).*: $1apple-touch-icon.png
