--- 
auth_file: /home/mm6/murlsh_users
description: URLs found interesting by Matthew M. Boedicker.
db_file: murlsh.db
feed_file: atom.xml
gravatar_size: 32
num_posts_feed: 25
num_posts_page: 100
page_title: mmb url share
root_url: http://matthewm.boedicker.org/urlshare/
css_prefix: css/
img_prefix: img/
js_prefix: js/
swf_prefix: swf/
css_files:
- screen.css
